package com.zl.drl.basic;

import com.zl.basic.ActivationGroup
dialect  "mvel"

rule "ActivationGroupO"
    activation-group "test"
    when
        $A : ActivationGroup( groupId > 0)
    then
        System.out.println("current groupId is greater than 0 int test group!");
end

rule "ActivationGroupM"
    activation-group "test"
    when
        $A : ActivationGroup(groupId > 5)
    then
        System.out.println("current groupId is greater than 5 in test group!");
end

rule "ActivationGroupTh"
    activation-group "official"
    when
        $A : ActivationGroup(groupId > 0)
    then
        System.out.println("current groupId is greater than 0 in official group!");
end

rule "ActivationGroupF"
    activation-group "official"
    when
        $A : ActivationGroup(groupId > 5)
    then
        System.out.println("current groupId is greater than 5 in official group!");
end
