package com.zl.drl.basic;

import com.zl.basic.NoLoop
import java.util.concurrent.TimeUnit
dialect  "mvel"

rule "NoLoopO"
salience 2
    no-loop true
    when
        $n : NoLoop(num > 0)
    then
        System.out.println("current num is" + $n.getNum());

        TimeUnit.SECONDS.sleep(1);
        if($n.getName().equalsIgnoreCase("score")){
            System.out.println("current name is=" + $n.getName());
            $n.setNum($n.getNum() + 1);
        }
        modify($n){setNum($n.getNum() + 1)}
end

rule "NoLoopT"

    when
        $n : NoLoop(name == "score")
    then
        System.out.println("current score is =>" + $n.getNum());
end
