package com.zl.person
import com.alibaba.fastjson.JSONObject

rule "SameOne"
    lock-on-active true
    salience 3
    when
        $student : Student(age == 25, name == "zhouliang", certNo == "123456")
    then
        System.out.println("student info is =>" + JSONObject.toJSONString($student));
end

rule "Two"
    dialect "mvel"
    lock-on-active true
    salience 2
    when
        $doctor : Doctor(age == 25, name == "zhouliang", certNo == "123456")
        $student : Student(age == 25, name == "zhouliang", certNo == "123456")
        $sameOne : SameOne()
    then
        System.out.println("this is the same one person!");
        modify($sameOne){
        name = $doctor.getName,
        setMobile($student.mobile),
        certNo = $student.certNo,
        ifSamePerson = true};
end


